### ISSUE TITLE
评论是按时间正序还是倒序排列，这是个问题，可以考虑做一个配置选项。

### ISSUE THREAD

**Issue by mzlogin** [mzlogin/guanggoo-android#20]

**Comment by fengguoqing** [comment]
支持，默认的倒序其实很不方便，有很多人一次发表不完的文章，在后面楼层发表，就被放到了最下面，很不利于阅读。

**Comment by mzlogin** [comment]
是的，确实有这种情况。正序更适合大家的使用习惯。代码里已经修改为正序显示评论，下一次发版时会带上了。
