### ISSUE TITLE
登录状态不能保持

### ISSUE THREAD

**Issue by fengguoqing** [mzlogin/guanggoo-android#55]
昨天晚上登陆的，今天早上来看又需要登录了，请问能否将登录状态保持住，每次输入账号密码挺麻烦的，谢谢！

**Comment by mzlogin** [comment]
设计的是在打开 APP 的时候带 cookie 发个请求判断响应里的内容，来自动保持登录状态的，但是取决于网络状态和网站服务的状态，有可能会尝试失败，如果不想输入账号密码可以杀掉 APP 重新进一下。

这块目前的体验确实不好，我想想办法看怎么优化。你有什么好的建议也欢迎提出~

我目前能想到的一个优化是省掉这个只判断登录状态的请求，复用请求帖子列表的请求来判断登录状态。

**Comment by mzlogin** [comment]
Fixed.

加了一点补偿机制。
