### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [mzlogin/guanggoo-android#70]
请问是否可以将应用打包发布到 [F-Droid](https://f-droid.org)？

**Comment by mzlogin** [comment]
发布可以的～不太建议自行打包，我这边有发布安装包：https://github.com/mzlogin/guanggoo-android/releases

**Comment by linsui** [comment]
谢谢！F-Droid 要求从源码构建所以只能自行打包。

**Comment by linsui** [comment]
我开了一个 [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10542)。

**Comment by mzlogin** [comment]
好的。

**Comment by linsui** [comment]
请问 android.permission.READ_PHONE_STATE 这项权限是做什么用的？

**Comment by mzlogin** [comment]
> 请问 android.permission.READ_PHONE_STATE 这项权限是做什么用的？

这个是集成腾讯 Bugly SDK（用作崩溃上报、版本升级）的过程中引入的，相关的说明可以参考 Bugly 文档，比如 <https://bugly.qq.com/docs/user-guide/faq-android/?v=1.0.0#1-bugly>，详细的用途我大致看了下也没找到非常具体的，有可能是读取设备 ID、网络状态之类的，不过应用并没有显式申请过此权限，对应的操作它应该也做不了，后续可以抽空看看去掉有无影响。

**Comment by linsui** [comment]
我已经移除了 Bugly，因为它不是开源的，所以我会直接移除这个权限，应该不会有影响。谢谢！

**Comment by linsui** [comment]
MR 已合并！大概两到三天内会进入存储库。F-Droid 徽标

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/org.mazhuang.guanggoo)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/org.mazhuang.guanggoo)
```

感谢你的帮助和支持！

**Comment by mzlogin** [comment]
不客气
